apiVersion: v1
kind: ConfigMap
metadata:
  name: cooldude-cm
data:
  appsettings.json: |-
    {
      
      "FilePaths": {
        "ClientFileLocation": "/data/maps",
        "GlobalFilesLocation": "/data/global"
      },
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cooldude
  labels:
    app: cooldude
spec:
  selector:
    matchLabels:
      app: cooldude
  replicas: 1
  template:
    metadata:
      labels:
        app: cooldude
    spec:
      containers:
      - name: cooldude
        image: 515*********.dkr.ecr.ap-south-1.amazonaws.com/cooldude:latest
        volumeMounts:
        - name: common-pv-1
          mountPath: /data
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: common-pv-1
        hostPath:
          path: /data/
      - name: config-volume
        configMap:
          name: cooldude-cm

---

apiVersion: v1
kind: Service
metadata:
  name: cooldude
spec:
  selector:
    app: cooldude
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cooldude-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: <host_namse
    http:
      paths:
        - path: /cooldude
          pathType: Prefix
          backend:
            service:
              name: cooldude
              port:
                number: 8080
