apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  restartPolicy: Never
  containers:
  - name: main-container
    image: busybox
    command: ["sleep", "120"]
    volumeMounts:
    - name: common-pv-1
      mountPath: /data
  initContainers:
  - name: download-files
    image: alpine
    command:
    - sh
    - -c
    - |
      apk add --no-cache curl \
      && if [ ! -d "/data/global/pdf" ]; then \
            mkdir -p /data/global/pdf; \
         fi \
      && curl -o /data/global/pdf/link1.pdf https://link1 \
      && curl -o /data/global/pdf.pdf https://link2
    volumeMounts:
    - name: common-pv-1
      mountPath: /data
  volumes:
  - name: common-pv-1
    hostPath:
      path: /data
