apiVersion: v1
kind: PersistentVolume
metadata:
  name: common-pv-1
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: <your_ebs_volume_id>
    fsType: ext4
